name: ipecstudentsapp
description: IPEC Student's App 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 5.0.1+36

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic:
    git:
        url: https://github.com/tsvillain/Flutter-Neumorphic.git
  adaptive_theme: ^2.2.0
  circular_profile_avatar: ^2.0.0
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.2.0
  dio: ^4.0.0
  equatable: ^2.0.2
  # firebase_analytics: ^8.1.0
  polls: ^1.0.1
  introduction_screen: ^2.1.0
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_database: ^8.2.0 
  firebase_messaging: ^11.2.5
  fl_chart: ^0.40.2
  flutter_bloc: ^7.1.0
  flutter_share: ^2.0.0
  flutter_svg: ^0.22.0
  flutter_markdown: ^0.6.10
  html: ^0.15.0
  intl: ^0.17.0
  lottie: ^1.0.1
  mantras:
    git:
      url: https://github.com/uttusharma/mantras.git
  provider: ^6.0.2
  share: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0
  syncfusion_flutter_pdfviewer: ^19.3.55-beta
  url_launcher: ^6.0.4
  string_validator: ^0.3.0
  image_picker: ^0.8.0+1
  webview_flutter: ^2.0.7
  firebase_storage: ^8.1.1
  giphy_picker: ^2.0.0
  pull_to_refresh: ^2.0.0
  upgrader: ^3.10.0
  profanity_filter: ^2.0.0
  sweetsheet: ^0.3.1
  in_app_review: ^2.0.4
  is_first_run: ^1.0.0
  rainbow_color: ^2.0.1
  # to build in android remove this
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: null
  flutter_native_splash: ^1.2.3
  # flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anim/
    - assets/icons/

  fonts:
    - family: averta
      fonts:
        - asset: fonts/averta/Averta-Regular.ttf
        - asset: fonts/averta/Averta-Bold.ttf
          weight: 500

flutter_native_splash:
  image: assets/images/logo.png
  color: "#FFFFFF"
